[features]
seeds = false
skip-lint = false
[programs.devnet]
demo = "4RJD7nTLNu3AKGzu82FBLjwKZDJrczBfamffteQRvfV3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/justinlee/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
